version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "80:8000"  # Открываем порт 80 на сервере и направляем его на 8000 внутри контейнера
    restart: always
    env_file:
      - .env       # Если у вас есть файл с переменными окружения (пароли, секретные ключи)
    volumes:
      # Если вам нужно, чтобы загруженные пользователями файлы сохранялись на сервере
      # - ./uploads:/app/uploads 
      - ./static:/app/static # Опционально: если хотите менять CSS/JS без пересборки образа